### ISSUE TITLE
Can't create file or directory, got a ENOENT from npm

### ISSUE THREAD

**Issue by pedropcruz** [serkanerip/vuemastery-dl#1]
Hello @serkanerip 

I'm getting this error, already tryed to change `downloadVideos`, but can't understand the real reason. I'm using WSL2, and you need to user xLaunch for opening chromium browser for getting all the links.

![image](https://user-images.githubusercontent.com/6757946/146551526-5bdd40fc-92e1-45f2-8a1e-c0e5524ab405.png)

Could you help me with this?

**Comment by jagarciavi** [comment]
Just create a 'downloads' folder in the root directory of the project

**Comment by pedropcruz** [comment]
> 

thanks! It solved, now have other problem, I can't download because the access is denied. Mey should login first?

**Comment by jagarciavi** [comment]
> > Just create a 'downloads' folder in the root directory of the project
> 
> thanks! It solved, now have other problem, I can't download because the access is denied. Maybe should login first?

You have to include your login credentials in a .env, as README explains

**Comment by pedropcruz** [comment]
> > > Just create a 'downloads' folder in the root directory of the project
> > 
> > 
> > thanks! It solved, now have other problem, I can't download because the access is denied. Maybe should login first?
> 
> You have to include your login credentials in a .env, as README explains

Yeap, have done everything like it's mention on README.md . But for some reason, after sometime you loose your auth. But thanks for the info :)

**Comment by rodrigojmr** [comment]
Hopefully this should help any directory issues.
#2

**Comment by serkanerip** [comment]
@pedropcruz video url's have a timeout if your downloading process takes too much time remained urls might expire
