### ISSUE TITLE
can't fetching videos links 

### ISSUE THREAD

**Issue by Abdelrahman-Mahmoud-Dev** [serkanerip/vuemastery-dl#3]
i get this error after start server node , cannot fetching videos links to create course-video-lists directory
![image](https://user-images.githubusercontent.com/64368991/146628274-1a947727-cd11-4c2c-b491-d8f0debf112a.png)

Could you help me with this?

**Comment by rodrigojmr** [comment]
Can't help with the iframe but I see on the second error (ENOENT) you have conflicting slashes on the directory, so you must be using windows. This #2 should help with that.

**Comment by Abdelrahman-Mahmoud-Dev** [comment]
thanks for your interest! but unfortunately not work because error with the iframe timeout

**Comment by niekysu** [comment]
@rodrigojmr **Any idea how to fix this?** 

![Anmerkung 2021-12-18 231452](https://user-images.githubusercontent.com/45577529/146656934-63f89211-155f-44ad-9a94-bbbbca456a5c.png)

Thanks for the #2 Fix . I was able to reduce some errors.

![image](https://user-images.githubusercontent.com/45577529/146657004-6ce79d22-cb62-4012-a135-a6de8d72070a.png)

**Comment by serkanerip** [comment]
fixed
