### ISSUE TITLE
permission denied error on video download

### ISSUE THREAD

**Issue by abhineettandon** [serkanerip/vuemastery-dl#4]
Alright, so this was working before last commit but now whenever i run `scripts/download-from-json.js course-video-lists/all.json` this gives me `permission denied` error. I ever tried to create the `downloads` directory manually but got the same results. 

Anyone else facing this issue?

![Screenshot 2021-12-19 at 7 44 20 PM](https://user-images.githubusercontent.com/16497456/146677998-0b988421-7d4f-4adb-97a4-8d4ab9f8d1e8.png)

**Comment by waseeld** [comment]
what ??

your comannd like : `scripts/download-from-json.js course-video-lists/all.json`

it most be : `node scripts/download-from-json.js course-video-lists/all.json` right ?

**Comment by abhineettandon** [comment]
Oh crap 🤦‍♂️
