### ISSUE TITLE
SyntaxError: unexpected token '}'

### ISSUE THREAD

**Issue by niekysu** [serkanerip/vuemastery-dl#6]
error message while running `node index.js` command
Any idea how to fix this:

![Anmerkung 2021-12-18 231452](https://user-images.githubusercontent.com/45577529/146686787-662ca435-5df4-452b-a191-802b93e5118f.png)

**Comment by rodrigojmr** [comment]
That's a syntax issue in JS, as it points out in the getCourseVideoList.js file at line 99, character 42. I cloned the repo again after my PR and haven't been able to replicate this. Please make sure you haven't modified the code, as I also don't have any syntax issues in VSCode.

**Comment by alext100** [comment]
I have the same error. Didn't touch anything in the code.

**Comment by alext100** [comment]
Got it. In getCourseVideoList, the problem in the string  
let finString = newString.split(']},"lang":"en","sentry":')[0];

To fix it you should console.log newString and find there "lang": ??? and then change founded language in the finString.
